// Generated by CIRCT firtool-1.49.0
module SinglePe(
  input  [31:0] io_in_a,
                io_in_b,
  input         io_mode,
  output [31:0] io_out
);

  wire [31:0] diff = io_in_a > io_in_b ? io_in_a - io_in_b : io_in_b - io_in_a;
  assign io_out = io_mode ? io_in_a * io_in_b : diff * diff;
endmodule

module AddTree(
  input         clock,
                reset,
  input  [31:0] io_input_0_a,
                io_input_0_b,
                io_input_1_a,
                io_input_1_b,
                io_input_2_a,
                io_input_2_b,
                io_input_3_a,
                io_input_3_b,
                io_input_4_a,
                io_input_4_b,
                io_input_5_a,
                io_input_5_b,
                io_input_6_a,
                io_input_6_b,
                io_input_7_a,
                io_input_7_b,
  input         io_mode,
  output [31:0] io_output
);

  wire [31:0] _pes_7_io_out;
  wire [31:0] _pes_6_io_out;
  wire [31:0] _pes_5_io_out;
  wire [31:0] _pes_4_io_out;
  wire [31:0] _pes_3_io_out;
  wire [31:0] _pes_2_io_out;
  wire [31:0] _pes_1_io_out;
  wire [31:0] _pes_0_io_out;
  reg  [31:0] io_output_left_left_left;
  reg  [31:0] io_output_left_left_right;
  reg  [31:0] io_output_left_left;
  reg  [31:0] io_output_left_right_left;
  reg  [31:0] io_output_left_right_right;
  reg  [31:0] io_output_left_right;
  reg  [31:0] io_output_left;
  reg  [31:0] io_output_right_left_left;
  reg  [31:0] io_output_right_left_right;
  reg  [31:0] io_output_right_left;
  reg  [31:0] io_output_right_right_left;
  reg  [31:0] io_output_right_right_right;
  reg  [31:0] io_output_right_right;
  reg  [31:0] io_output_right;
  always @(posedge clock) begin
    io_output_left_left_left <= _pes_0_io_out;
    io_output_left_left_right <= _pes_1_io_out;
    io_output_left_left <= io_output_left_left_left + io_output_left_left_right;
    io_output_left_right_left <= _pes_2_io_out;
    io_output_left_right_right <= _pes_3_io_out;
    io_output_left_right <= io_output_left_right_left + io_output_left_right_right;
    io_output_left <= io_output_left_left + io_output_left_right;
    io_output_right_left_left <= _pes_4_io_out;
    io_output_right_left_right <= _pes_5_io_out;
    io_output_right_left <= io_output_right_left_left + io_output_right_left_right;
    io_output_right_right_left <= _pes_6_io_out;
    io_output_right_right_right <= _pes_7_io_out;
    io_output_right_right <= io_output_right_right_left + io_output_right_right_right;
    io_output_right <= io_output_right_left + io_output_right_right;
  end // always @(posedge)
  SinglePe pes_0 (
    .io_in_a (io_input_0_a),
    .io_in_b (io_input_0_b),
    .io_mode (io_mode),
    .io_out  (_pes_0_io_out)
  );
  SinglePe pes_1 (
    .io_in_a (io_input_1_a),
    .io_in_b (io_input_1_b),
    .io_mode (io_mode),
    .io_out  (_pes_1_io_out)
  );
  SinglePe pes_2 (
    .io_in_a (io_input_2_a),
    .io_in_b (io_input_2_b),
    .io_mode (io_mode),
    .io_out  (_pes_2_io_out)
  );
  SinglePe pes_3 (
    .io_in_a (io_input_3_a),
    .io_in_b (io_input_3_b),
    .io_mode (io_mode),
    .io_out  (_pes_3_io_out)
  );
  SinglePe pes_4 (
    .io_in_a (io_input_4_a),
    .io_in_b (io_input_4_b),
    .io_mode (io_mode),
    .io_out  (_pes_4_io_out)
  );
  SinglePe pes_5 (
    .io_in_a (io_input_5_a),
    .io_in_b (io_input_5_b),
    .io_mode (io_mode),
    .io_out  (_pes_5_io_out)
  );
  SinglePe pes_6 (
    .io_in_a (io_input_6_a),
    .io_in_b (io_input_6_b),
    .io_mode (io_mode),
    .io_out  (_pes_6_io_out)
  );
  SinglePe pes_7 (
    .io_in_a (io_input_7_a),
    .io_in_b (io_input_7_b),
    .io_mode (io_mode),
    .io_out  (_pes_7_io_out)
  );
  assign io_output = io_output_left + io_output_right;
endmodule

