// Generated by CIRCT firtool-1.49.0
module SinglePe(
  input  [31:0] io_in_a,
                io_in_b,
  input         io_mode,
  output [31:0] io_out
);

  wire [31:0] diff = io_in_a > io_in_b ? io_in_a - io_in_b : io_in_b - io_in_a;
  assign io_out = io_mode ? io_in_a * io_in_b : diff * diff;
endmodule

module AddTree(
  input         clock,
                reset,
  input  [31:0] io_input_0_a,
                io_input_0_b,
                io_input_1_a,
                io_input_1_b,
                io_input_2_a,
                io_input_2_b,
                io_input_3_a,
                io_input_3_b,
                io_input_4_a,
                io_input_4_b,
                io_input_5_a,
                io_input_5_b,
                io_input_6_a,
                io_input_6_b,
                io_input_7_a,
                io_input_7_b,
                io_input_8_a,
                io_input_8_b,
                io_input_9_a,
                io_input_9_b,
                io_input_10_a,
                io_input_10_b,
                io_input_11_a,
                io_input_11_b,
                io_input_12_a,
                io_input_12_b,
                io_input_13_a,
                io_input_13_b,
                io_input_14_a,
                io_input_14_b,
                io_input_15_a,
                io_input_15_b,
                io_input_16_a,
                io_input_16_b,
                io_input_17_a,
                io_input_17_b,
                io_input_18_a,
                io_input_18_b,
                io_input_19_a,
                io_input_19_b,
                io_input_20_a,
                io_input_20_b,
                io_input_21_a,
                io_input_21_b,
                io_input_22_a,
                io_input_22_b,
                io_input_23_a,
                io_input_23_b,
                io_input_24_a,
                io_input_24_b,
                io_input_25_a,
                io_input_25_b,
                io_input_26_a,
                io_input_26_b,
                io_input_27_a,
                io_input_27_b,
                io_input_28_a,
                io_input_28_b,
                io_input_29_a,
                io_input_29_b,
                io_input_30_a,
                io_input_30_b,
                io_input_31_a,
                io_input_31_b,
  input         io_mode,
  output [31:0] io_output
);

  wire [31:0] _pes_31_io_out;
  wire [31:0] _pes_30_io_out;
  wire [31:0] _pes_29_io_out;
  wire [31:0] _pes_28_io_out;
  wire [31:0] _pes_27_io_out;
  wire [31:0] _pes_26_io_out;
  wire [31:0] _pes_25_io_out;
  wire [31:0] _pes_24_io_out;
  wire [31:0] _pes_23_io_out;
  wire [31:0] _pes_22_io_out;
  wire [31:0] _pes_21_io_out;
  wire [31:0] _pes_20_io_out;
  wire [31:0] _pes_19_io_out;
  wire [31:0] _pes_18_io_out;
  wire [31:0] _pes_17_io_out;
  wire [31:0] _pes_16_io_out;
  wire [31:0] _pes_15_io_out;
  wire [31:0] _pes_14_io_out;
  wire [31:0] _pes_13_io_out;
  wire [31:0] _pes_12_io_out;
  wire [31:0] _pes_11_io_out;
  wire [31:0] _pes_10_io_out;
  wire [31:0] _pes_9_io_out;
  wire [31:0] _pes_8_io_out;
  wire [31:0] _pes_7_io_out;
  wire [31:0] _pes_6_io_out;
  wire [31:0] _pes_5_io_out;
  wire [31:0] _pes_4_io_out;
  wire [31:0] _pes_3_io_out;
  wire [31:0] _pes_2_io_out;
  wire [31:0] _pes_1_io_out;
  wire [31:0] _pes_0_io_out;
  reg  [31:0] io_output_left_left_left_left_left;
  reg  [31:0] io_output_left_left_left_left_right;
  reg  [31:0] io_output_left_left_left_left;
  reg  [31:0] io_output_left_left_left_right_left;
  reg  [31:0] io_output_left_left_left_right_right;
  reg  [31:0] io_output_left_left_left_right;
  reg  [31:0] io_output_left_left_left;
  reg  [31:0] io_output_left_left_right_left_left;
  reg  [31:0] io_output_left_left_right_left_right;
  reg  [31:0] io_output_left_left_right_left;
  reg  [31:0] io_output_left_left_right_right_left;
  reg  [31:0] io_output_left_left_right_right_right;
  reg  [31:0] io_output_left_left_right_right;
  reg  [31:0] io_output_left_left_right;
  reg  [31:0] io_output_left_left;
  reg  [31:0] io_output_left_right_left_left_left;
  reg  [31:0] io_output_left_right_left_left_right;
  reg  [31:0] io_output_left_right_left_left;
  reg  [31:0] io_output_left_right_left_right_left;
  reg  [31:0] io_output_left_right_left_right_right;
  reg  [31:0] io_output_left_right_left_right;
  reg  [31:0] io_output_left_right_left;
  reg  [31:0] io_output_left_right_right_left_left;
  reg  [31:0] io_output_left_right_right_left_right;
  reg  [31:0] io_output_left_right_right_left;
  reg  [31:0] io_output_left_right_right_right_left;
  reg  [31:0] io_output_left_right_right_right_right;
  reg  [31:0] io_output_left_right_right_right;
  reg  [31:0] io_output_left_right_right;
  reg  [31:0] io_output_left_right;
  reg  [31:0] io_output_left;
  reg  [31:0] io_output_right_left_left_left_left;
  reg  [31:0] io_output_right_left_left_left_right;
  reg  [31:0] io_output_right_left_left_left;
  reg  [31:0] io_output_right_left_left_right_left;
  reg  [31:0] io_output_right_left_left_right_right;
  reg  [31:0] io_output_right_left_left_right;
  reg  [31:0] io_output_right_left_left;
  reg  [31:0] io_output_right_left_right_left_left;
  reg  [31:0] io_output_right_left_right_left_right;
  reg  [31:0] io_output_right_left_right_left;
  reg  [31:0] io_output_right_left_right_right_left;
  reg  [31:0] io_output_right_left_right_right_right;
  reg  [31:0] io_output_right_left_right_right;
  reg  [31:0] io_output_right_left_right;
  reg  [31:0] io_output_right_left;
  reg  [31:0] io_output_right_right_left_left_left;
  reg  [31:0] io_output_right_right_left_left_right;
  reg  [31:0] io_output_right_right_left_left;
  reg  [31:0] io_output_right_right_left_right_left;
  reg  [31:0] io_output_right_right_left_right_right;
  reg  [31:0] io_output_right_right_left_right;
  reg  [31:0] io_output_right_right_left;
  reg  [31:0] io_output_right_right_right_left_left;
  reg  [31:0] io_output_right_right_right_left_right;
  reg  [31:0] io_output_right_right_right_left;
  reg  [31:0] io_output_right_right_right_right_left;
  reg  [31:0] io_output_right_right_right_right_right;
  reg  [31:0] io_output_right_right_right_right;
  reg  [31:0] io_output_right_right_right;
  reg  [31:0] io_output_right_right;
  reg  [31:0] io_output_right;
  always @(posedge clock) begin
    io_output_left_left_left_left_left <= _pes_0_io_out;
    io_output_left_left_left_left_right <= _pes_1_io_out;
    io_output_left_left_left_left <=
      io_output_left_left_left_left_left + io_output_left_left_left_left_right;
    io_output_left_left_left_right_left <= _pes_2_io_out;
    io_output_left_left_left_right_right <= _pes_3_io_out;
    io_output_left_left_left_right <=
      io_output_left_left_left_right_left + io_output_left_left_left_right_right;
    io_output_left_left_left <=
      io_output_left_left_left_left + io_output_left_left_left_right;
    io_output_left_left_right_left_left <= _pes_4_io_out;
    io_output_left_left_right_left_right <= _pes_5_io_out;
    io_output_left_left_right_left <=
      io_output_left_left_right_left_left + io_output_left_left_right_left_right;
    io_output_left_left_right_right_left <= _pes_6_io_out;
    io_output_left_left_right_right_right <= _pes_7_io_out;
    io_output_left_left_right_right <=
      io_output_left_left_right_right_left + io_output_left_left_right_right_right;
    io_output_left_left_right <=
      io_output_left_left_right_left + io_output_left_left_right_right;
    io_output_left_left <= io_output_left_left_left + io_output_left_left_right;
    io_output_left_right_left_left_left <= _pes_8_io_out;
    io_output_left_right_left_left_right <= _pes_9_io_out;
    io_output_left_right_left_left <=
      io_output_left_right_left_left_left + io_output_left_right_left_left_right;
    io_output_left_right_left_right_left <= _pes_10_io_out;
    io_output_left_right_left_right_right <= _pes_11_io_out;
    io_output_left_right_left_right <=
      io_output_left_right_left_right_left + io_output_left_right_left_right_right;
    io_output_left_right_left <=
      io_output_left_right_left_left + io_output_left_right_left_right;
    io_output_left_right_right_left_left <= _pes_12_io_out;
    io_output_left_right_right_left_right <= _pes_13_io_out;
    io_output_left_right_right_left <=
      io_output_left_right_right_left_left + io_output_left_right_right_left_right;
    io_output_left_right_right_right_left <= _pes_14_io_out;
    io_output_left_right_right_right_right <= _pes_15_io_out;
    io_output_left_right_right_right <=
      io_output_left_right_right_right_left + io_output_left_right_right_right_right;
    io_output_left_right_right <=
      io_output_left_right_right_left + io_output_left_right_right_right;
    io_output_left_right <= io_output_left_right_left + io_output_left_right_right;
    io_output_left <= io_output_left_left + io_output_left_right;
    io_output_right_left_left_left_left <= _pes_16_io_out;
    io_output_right_left_left_left_right <= _pes_17_io_out;
    io_output_right_left_left_left <=
      io_output_right_left_left_left_left + io_output_right_left_left_left_right;
    io_output_right_left_left_right_left <= _pes_18_io_out;
    io_output_right_left_left_right_right <= _pes_19_io_out;
    io_output_right_left_left_right <=
      io_output_right_left_left_right_left + io_output_right_left_left_right_right;
    io_output_right_left_left <=
      io_output_right_left_left_left + io_output_right_left_left_right;
    io_output_right_left_right_left_left <= _pes_20_io_out;
    io_output_right_left_right_left_right <= _pes_21_io_out;
    io_output_right_left_right_left <=
      io_output_right_left_right_left_left + io_output_right_left_right_left_right;
    io_output_right_left_right_right_left <= _pes_22_io_out;
    io_output_right_left_right_right_right <= _pes_23_io_out;
    io_output_right_left_right_right <=
      io_output_right_left_right_right_left + io_output_right_left_right_right_right;
    io_output_right_left_right <=
      io_output_right_left_right_left + io_output_right_left_right_right;
    io_output_right_left <= io_output_right_left_left + io_output_right_left_right;
    io_output_right_right_left_left_left <= _pes_24_io_out;
    io_output_right_right_left_left_right <= _pes_25_io_out;
    io_output_right_right_left_left <=
      io_output_right_right_left_left_left + io_output_right_right_left_left_right;
    io_output_right_right_left_right_left <= _pes_26_io_out;
    io_output_right_right_left_right_right <= _pes_27_io_out;
    io_output_right_right_left_right <=
      io_output_right_right_left_right_left + io_output_right_right_left_right_right;
    io_output_right_right_left <=
      io_output_right_right_left_left + io_output_right_right_left_right;
    io_output_right_right_right_left_left <= _pes_28_io_out;
    io_output_right_right_right_left_right <= _pes_29_io_out;
    io_output_right_right_right_left <=
      io_output_right_right_right_left_left + io_output_right_right_right_left_right;
    io_output_right_right_right_right_left <= _pes_30_io_out;
    io_output_right_right_right_right_right <= _pes_31_io_out;
    io_output_right_right_right_right <=
      io_output_right_right_right_right_left + io_output_right_right_right_right_right;
    io_output_right_right_right <=
      io_output_right_right_right_left + io_output_right_right_right_right;
    io_output_right_right <= io_output_right_right_left + io_output_right_right_right;
    io_output_right <= io_output_right_left + io_output_right_right;
  end // always @(posedge)
  SinglePe pes_0 (
    .io_in_a (io_input_0_a),
    .io_in_b (io_input_0_b),
    .io_mode (io_mode),
    .io_out  (_pes_0_io_out)
  );
  SinglePe pes_1 (
    .io_in_a (io_input_1_a),
    .io_in_b (io_input_1_b),
    .io_mode (io_mode),
    .io_out  (_pes_1_io_out)
  );
  SinglePe pes_2 (
    .io_in_a (io_input_2_a),
    .io_in_b (io_input_2_b),
    .io_mode (io_mode),
    .io_out  (_pes_2_io_out)
  );
  SinglePe pes_3 (
    .io_in_a (io_input_3_a),
    .io_in_b (io_input_3_b),
    .io_mode (io_mode),
    .io_out  (_pes_3_io_out)
  );
  SinglePe pes_4 (
    .io_in_a (io_input_4_a),
    .io_in_b (io_input_4_b),
    .io_mode (io_mode),
    .io_out  (_pes_4_io_out)
  );
  SinglePe pes_5 (
    .io_in_a (io_input_5_a),
    .io_in_b (io_input_5_b),
    .io_mode (io_mode),
    .io_out  (_pes_5_io_out)
  );
  SinglePe pes_6 (
    .io_in_a (io_input_6_a),
    .io_in_b (io_input_6_b),
    .io_mode (io_mode),
    .io_out  (_pes_6_io_out)
  );
  SinglePe pes_7 (
    .io_in_a (io_input_7_a),
    .io_in_b (io_input_7_b),
    .io_mode (io_mode),
    .io_out  (_pes_7_io_out)
  );
  SinglePe pes_8 (
    .io_in_a (io_input_8_a),
    .io_in_b (io_input_8_b),
    .io_mode (io_mode),
    .io_out  (_pes_8_io_out)
  );
  SinglePe pes_9 (
    .io_in_a (io_input_9_a),
    .io_in_b (io_input_9_b),
    .io_mode (io_mode),
    .io_out  (_pes_9_io_out)
  );
  SinglePe pes_10 (
    .io_in_a (io_input_10_a),
    .io_in_b (io_input_10_b),
    .io_mode (io_mode),
    .io_out  (_pes_10_io_out)
  );
  SinglePe pes_11 (
    .io_in_a (io_input_11_a),
    .io_in_b (io_input_11_b),
    .io_mode (io_mode),
    .io_out  (_pes_11_io_out)
  );
  SinglePe pes_12 (
    .io_in_a (io_input_12_a),
    .io_in_b (io_input_12_b),
    .io_mode (io_mode),
    .io_out  (_pes_12_io_out)
  );
  SinglePe pes_13 (
    .io_in_a (io_input_13_a),
    .io_in_b (io_input_13_b),
    .io_mode (io_mode),
    .io_out  (_pes_13_io_out)
  );
  SinglePe pes_14 (
    .io_in_a (io_input_14_a),
    .io_in_b (io_input_14_b),
    .io_mode (io_mode),
    .io_out  (_pes_14_io_out)
  );
  SinglePe pes_15 (
    .io_in_a (io_input_15_a),
    .io_in_b (io_input_15_b),
    .io_mode (io_mode),
    .io_out  (_pes_15_io_out)
  );
  SinglePe pes_16 (
    .io_in_a (io_input_16_a),
    .io_in_b (io_input_16_b),
    .io_mode (io_mode),
    .io_out  (_pes_16_io_out)
  );
  SinglePe pes_17 (
    .io_in_a (io_input_17_a),
    .io_in_b (io_input_17_b),
    .io_mode (io_mode),
    .io_out  (_pes_17_io_out)
  );
  SinglePe pes_18 (
    .io_in_a (io_input_18_a),
    .io_in_b (io_input_18_b),
    .io_mode (io_mode),
    .io_out  (_pes_18_io_out)
  );
  SinglePe pes_19 (
    .io_in_a (io_input_19_a),
    .io_in_b (io_input_19_b),
    .io_mode (io_mode),
    .io_out  (_pes_19_io_out)
  );
  SinglePe pes_20 (
    .io_in_a (io_input_20_a),
    .io_in_b (io_input_20_b),
    .io_mode (io_mode),
    .io_out  (_pes_20_io_out)
  );
  SinglePe pes_21 (
    .io_in_a (io_input_21_a),
    .io_in_b (io_input_21_b),
    .io_mode (io_mode),
    .io_out  (_pes_21_io_out)
  );
  SinglePe pes_22 (
    .io_in_a (io_input_22_a),
    .io_in_b (io_input_22_b),
    .io_mode (io_mode),
    .io_out  (_pes_22_io_out)
  );
  SinglePe pes_23 (
    .io_in_a (io_input_23_a),
    .io_in_b (io_input_23_b),
    .io_mode (io_mode),
    .io_out  (_pes_23_io_out)
  );
  SinglePe pes_24 (
    .io_in_a (io_input_24_a),
    .io_in_b (io_input_24_b),
    .io_mode (io_mode),
    .io_out  (_pes_24_io_out)
  );
  SinglePe pes_25 (
    .io_in_a (io_input_25_a),
    .io_in_b (io_input_25_b),
    .io_mode (io_mode),
    .io_out  (_pes_25_io_out)
  );
  SinglePe pes_26 (
    .io_in_a (io_input_26_a),
    .io_in_b (io_input_26_b),
    .io_mode (io_mode),
    .io_out  (_pes_26_io_out)
  );
  SinglePe pes_27 (
    .io_in_a (io_input_27_a),
    .io_in_b (io_input_27_b),
    .io_mode (io_mode),
    .io_out  (_pes_27_io_out)
  );
  SinglePe pes_28 (
    .io_in_a (io_input_28_a),
    .io_in_b (io_input_28_b),
    .io_mode (io_mode),
    .io_out  (_pes_28_io_out)
  );
  SinglePe pes_29 (
    .io_in_a (io_input_29_a),
    .io_in_b (io_input_29_b),
    .io_mode (io_mode),
    .io_out  (_pes_29_io_out)
  );
  SinglePe pes_30 (
    .io_in_a (io_input_30_a),
    .io_in_b (io_input_30_b),
    .io_mode (io_mode),
    .io_out  (_pes_30_io_out)
  );
  SinglePe pes_31 (
    .io_in_a (io_input_31_a),
    .io_in_b (io_input_31_b),
    .io_mode (io_mode),
    .io_out  (_pes_31_io_out)
  );
  assign io_output = io_output_left + io_output_right;
endmodule

