// Generated by CIRCT firtool-1.49.0
module SinglePe(
  input  [31:0] io_in_a,
                io_in_b,
  input         io_mode,
  output [31:0] io_out
);

  wire [31:0] diff = io_in_a > io_in_b ? io_in_a - io_in_b : io_in_b - io_in_a;
  assign io_out = io_mode ? io_in_a * io_in_b : diff * diff;
endmodule

module AddTree(
  input         clock,
                reset,
  input  [31:0] io_input_0_a,
                io_input_0_b,
                io_input_1_a,
                io_input_1_b,
                io_input_2_a,
                io_input_2_b,
                io_input_3_a,
                io_input_3_b,
                io_input_4_a,
                io_input_4_b,
                io_input_5_a,
                io_input_5_b,
                io_input_6_a,
                io_input_6_b,
                io_input_7_a,
                io_input_7_b,
                io_input_8_a,
                io_input_8_b,
                io_input_9_a,
                io_input_9_b,
                io_input_10_a,
                io_input_10_b,
                io_input_11_a,
                io_input_11_b,
                io_input_12_a,
                io_input_12_b,
                io_input_13_a,
                io_input_13_b,
                io_input_14_a,
                io_input_14_b,
                io_input_15_a,
                io_input_15_b,
                io_input_16_a,
                io_input_16_b,
                io_input_17_a,
                io_input_17_b,
                io_input_18_a,
                io_input_18_b,
                io_input_19_a,
                io_input_19_b,
                io_input_20_a,
                io_input_20_b,
                io_input_21_a,
                io_input_21_b,
                io_input_22_a,
                io_input_22_b,
                io_input_23_a,
                io_input_23_b,
                io_input_24_a,
                io_input_24_b,
                io_input_25_a,
                io_input_25_b,
                io_input_26_a,
                io_input_26_b,
                io_input_27_a,
                io_input_27_b,
                io_input_28_a,
                io_input_28_b,
                io_input_29_a,
                io_input_29_b,
                io_input_30_a,
                io_input_30_b,
                io_input_31_a,
                io_input_31_b,
                io_input_32_a,
                io_input_32_b,
                io_input_33_a,
                io_input_33_b,
                io_input_34_a,
                io_input_34_b,
                io_input_35_a,
                io_input_35_b,
                io_input_36_a,
                io_input_36_b,
                io_input_37_a,
                io_input_37_b,
                io_input_38_a,
                io_input_38_b,
                io_input_39_a,
                io_input_39_b,
                io_input_40_a,
                io_input_40_b,
                io_input_41_a,
                io_input_41_b,
                io_input_42_a,
                io_input_42_b,
                io_input_43_a,
                io_input_43_b,
                io_input_44_a,
                io_input_44_b,
                io_input_45_a,
                io_input_45_b,
                io_input_46_a,
                io_input_46_b,
                io_input_47_a,
                io_input_47_b,
                io_input_48_a,
                io_input_48_b,
                io_input_49_a,
                io_input_49_b,
                io_input_50_a,
                io_input_50_b,
                io_input_51_a,
                io_input_51_b,
                io_input_52_a,
                io_input_52_b,
                io_input_53_a,
                io_input_53_b,
                io_input_54_a,
                io_input_54_b,
                io_input_55_a,
                io_input_55_b,
                io_input_56_a,
                io_input_56_b,
                io_input_57_a,
                io_input_57_b,
                io_input_58_a,
                io_input_58_b,
                io_input_59_a,
                io_input_59_b,
                io_input_60_a,
                io_input_60_b,
                io_input_61_a,
                io_input_61_b,
                io_input_62_a,
                io_input_62_b,
                io_input_63_a,
                io_input_63_b,
  input         io_mode,
  output [31:0] io_output
);

  wire [31:0] _pes_63_io_out;
  wire [31:0] _pes_62_io_out;
  wire [31:0] _pes_61_io_out;
  wire [31:0] _pes_60_io_out;
  wire [31:0] _pes_59_io_out;
  wire [31:0] _pes_58_io_out;
  wire [31:0] _pes_57_io_out;
  wire [31:0] _pes_56_io_out;
  wire [31:0] _pes_55_io_out;
  wire [31:0] _pes_54_io_out;
  wire [31:0] _pes_53_io_out;
  wire [31:0] _pes_52_io_out;
  wire [31:0] _pes_51_io_out;
  wire [31:0] _pes_50_io_out;
  wire [31:0] _pes_49_io_out;
  wire [31:0] _pes_48_io_out;
  wire [31:0] _pes_47_io_out;
  wire [31:0] _pes_46_io_out;
  wire [31:0] _pes_45_io_out;
  wire [31:0] _pes_44_io_out;
  wire [31:0] _pes_43_io_out;
  wire [31:0] _pes_42_io_out;
  wire [31:0] _pes_41_io_out;
  wire [31:0] _pes_40_io_out;
  wire [31:0] _pes_39_io_out;
  wire [31:0] _pes_38_io_out;
  wire [31:0] _pes_37_io_out;
  wire [31:0] _pes_36_io_out;
  wire [31:0] _pes_35_io_out;
  wire [31:0] _pes_34_io_out;
  wire [31:0] _pes_33_io_out;
  wire [31:0] _pes_32_io_out;
  wire [31:0] _pes_31_io_out;
  wire [31:0] _pes_30_io_out;
  wire [31:0] _pes_29_io_out;
  wire [31:0] _pes_28_io_out;
  wire [31:0] _pes_27_io_out;
  wire [31:0] _pes_26_io_out;
  wire [31:0] _pes_25_io_out;
  wire [31:0] _pes_24_io_out;
  wire [31:0] _pes_23_io_out;
  wire [31:0] _pes_22_io_out;
  wire [31:0] _pes_21_io_out;
  wire [31:0] _pes_20_io_out;
  wire [31:0] _pes_19_io_out;
  wire [31:0] _pes_18_io_out;
  wire [31:0] _pes_17_io_out;
  wire [31:0] _pes_16_io_out;
  wire [31:0] _pes_15_io_out;
  wire [31:0] _pes_14_io_out;
  wire [31:0] _pes_13_io_out;
  wire [31:0] _pes_12_io_out;
  wire [31:0] _pes_11_io_out;
  wire [31:0] _pes_10_io_out;
  wire [31:0] _pes_9_io_out;
  wire [31:0] _pes_8_io_out;
  wire [31:0] _pes_7_io_out;
  wire [31:0] _pes_6_io_out;
  wire [31:0] _pes_5_io_out;
  wire [31:0] _pes_4_io_out;
  wire [31:0] _pes_3_io_out;
  wire [31:0] _pes_2_io_out;
  wire [31:0] _pes_1_io_out;
  wire [31:0] _pes_0_io_out;
  reg  [31:0] io_output_left_left_left_left_left_left;
  reg  [31:0] io_output_left_left_left_left_left_right;
  reg  [31:0] io_output_left_left_left_left_left;
  reg  [31:0] io_output_left_left_left_left_right_left;
  reg  [31:0] io_output_left_left_left_left_right_right;
  reg  [31:0] io_output_left_left_left_left_right;
  reg  [31:0] io_output_left_left_left_left;
  reg  [31:0] io_output_left_left_left_right_left_left;
  reg  [31:0] io_output_left_left_left_right_left_right;
  reg  [31:0] io_output_left_left_left_right_left;
  reg  [31:0] io_output_left_left_left_right_right_left;
  reg  [31:0] io_output_left_left_left_right_right_right;
  reg  [31:0] io_output_left_left_left_right_right;
  reg  [31:0] io_output_left_left_left_right;
  reg  [31:0] io_output_left_left_left;
  reg  [31:0] io_output_left_left_right_left_left_left;
  reg  [31:0] io_output_left_left_right_left_left_right;
  reg  [31:0] io_output_left_left_right_left_left;
  reg  [31:0] io_output_left_left_right_left_right_left;
  reg  [31:0] io_output_left_left_right_left_right_right;
  reg  [31:0] io_output_left_left_right_left_right;
  reg  [31:0] io_output_left_left_right_left;
  reg  [31:0] io_output_left_left_right_right_left_left;
  reg  [31:0] io_output_left_left_right_right_left_right;
  reg  [31:0] io_output_left_left_right_right_left;
  reg  [31:0] io_output_left_left_right_right_right_left;
  reg  [31:0] io_output_left_left_right_right_right_right;
  reg  [31:0] io_output_left_left_right_right_right;
  reg  [31:0] io_output_left_left_right_right;
  reg  [31:0] io_output_left_left_right;
  reg  [31:0] io_output_left_left;
  reg  [31:0] io_output_left_right_left_left_left_left;
  reg  [31:0] io_output_left_right_left_left_left_right;
  reg  [31:0] io_output_left_right_left_left_left;
  reg  [31:0] io_output_left_right_left_left_right_left;
  reg  [31:0] io_output_left_right_left_left_right_right;
  reg  [31:0] io_output_left_right_left_left_right;
  reg  [31:0] io_output_left_right_left_left;
  reg  [31:0] io_output_left_right_left_right_left_left;
  reg  [31:0] io_output_left_right_left_right_left_right;
  reg  [31:0] io_output_left_right_left_right_left;
  reg  [31:0] io_output_left_right_left_right_right_left;
  reg  [31:0] io_output_left_right_left_right_right_right;
  reg  [31:0] io_output_left_right_left_right_right;
  reg  [31:0] io_output_left_right_left_right;
  reg  [31:0] io_output_left_right_left;
  reg  [31:0] io_output_left_right_right_left_left_left;
  reg  [31:0] io_output_left_right_right_left_left_right;
  reg  [31:0] io_output_left_right_right_left_left;
  reg  [31:0] io_output_left_right_right_left_right_left;
  reg  [31:0] io_output_left_right_right_left_right_right;
  reg  [31:0] io_output_left_right_right_left_right;
  reg  [31:0] io_output_left_right_right_left;
  reg  [31:0] io_output_left_right_right_right_left_left;
  reg  [31:0] io_output_left_right_right_right_left_right;
  reg  [31:0] io_output_left_right_right_right_left;
  reg  [31:0] io_output_left_right_right_right_right_left;
  reg  [31:0] io_output_left_right_right_right_right_right;
  reg  [31:0] io_output_left_right_right_right_right;
  reg  [31:0] io_output_left_right_right_right;
  reg  [31:0] io_output_left_right_right;
  reg  [31:0] io_output_left_right;
  reg  [31:0] io_output_left;
  reg  [31:0] io_output_right_left_left_left_left_left;
  reg  [31:0] io_output_right_left_left_left_left_right;
  reg  [31:0] io_output_right_left_left_left_left;
  reg  [31:0] io_output_right_left_left_left_right_left;
  reg  [31:0] io_output_right_left_left_left_right_right;
  reg  [31:0] io_output_right_left_left_left_right;
  reg  [31:0] io_output_right_left_left_left;
  reg  [31:0] io_output_right_left_left_right_left_left;
  reg  [31:0] io_output_right_left_left_right_left_right;
  reg  [31:0] io_output_right_left_left_right_left;
  reg  [31:0] io_output_right_left_left_right_right_left;
  reg  [31:0] io_output_right_left_left_right_right_right;
  reg  [31:0] io_output_right_left_left_right_right;
  reg  [31:0] io_output_right_left_left_right;
  reg  [31:0] io_output_right_left_left;
  reg  [31:0] io_output_right_left_right_left_left_left;
  reg  [31:0] io_output_right_left_right_left_left_right;
  reg  [31:0] io_output_right_left_right_left_left;
  reg  [31:0] io_output_right_left_right_left_right_left;
  reg  [31:0] io_output_right_left_right_left_right_right;
  reg  [31:0] io_output_right_left_right_left_right;
  reg  [31:0] io_output_right_left_right_left;
  reg  [31:0] io_output_right_left_right_right_left_left;
  reg  [31:0] io_output_right_left_right_right_left_right;
  reg  [31:0] io_output_right_left_right_right_left;
  reg  [31:0] io_output_right_left_right_right_right_left;
  reg  [31:0] io_output_right_left_right_right_right_right;
  reg  [31:0] io_output_right_left_right_right_right;
  reg  [31:0] io_output_right_left_right_right;
  reg  [31:0] io_output_right_left_right;
  reg  [31:0] io_output_right_left;
  reg  [31:0] io_output_right_right_left_left_left_left;
  reg  [31:0] io_output_right_right_left_left_left_right;
  reg  [31:0] io_output_right_right_left_left_left;
  reg  [31:0] io_output_right_right_left_left_right_left;
  reg  [31:0] io_output_right_right_left_left_right_right;
  reg  [31:0] io_output_right_right_left_left_right;
  reg  [31:0] io_output_right_right_left_left;
  reg  [31:0] io_output_right_right_left_right_left_left;
  reg  [31:0] io_output_right_right_left_right_left_right;
  reg  [31:0] io_output_right_right_left_right_left;
  reg  [31:0] io_output_right_right_left_right_right_left;
  reg  [31:0] io_output_right_right_left_right_right_right;
  reg  [31:0] io_output_right_right_left_right_right;
  reg  [31:0] io_output_right_right_left_right;
  reg  [31:0] io_output_right_right_left;
  reg  [31:0] io_output_right_right_right_left_left_left;
  reg  [31:0] io_output_right_right_right_left_left_right;
  reg  [31:0] io_output_right_right_right_left_left;
  reg  [31:0] io_output_right_right_right_left_right_left;
  reg  [31:0] io_output_right_right_right_left_right_right;
  reg  [31:0] io_output_right_right_right_left_right;
  reg  [31:0] io_output_right_right_right_left;
  reg  [31:0] io_output_right_right_right_right_left_left;
  reg  [31:0] io_output_right_right_right_right_left_right;
  reg  [31:0] io_output_right_right_right_right_left;
  reg  [31:0] io_output_right_right_right_right_right_left;
  reg  [31:0] io_output_right_right_right_right_right_right;
  reg  [31:0] io_output_right_right_right_right_right;
  reg  [31:0] io_output_right_right_right_right;
  reg  [31:0] io_output_right_right_right;
  reg  [31:0] io_output_right_right;
  reg  [31:0] io_output_right;
  always @(posedge clock) begin
    io_output_left_left_left_left_left_left <= _pes_0_io_out;
    io_output_left_left_left_left_left_right <= _pes_1_io_out;
    io_output_left_left_left_left_left <=
      io_output_left_left_left_left_left_left + io_output_left_left_left_left_left_right;
    io_output_left_left_left_left_right_left <= _pes_2_io_out;
    io_output_left_left_left_left_right_right <= _pes_3_io_out;
    io_output_left_left_left_left_right <=
      io_output_left_left_left_left_right_left
      + io_output_left_left_left_left_right_right;
    io_output_left_left_left_left <=
      io_output_left_left_left_left_left + io_output_left_left_left_left_right;
    io_output_left_left_left_right_left_left <= _pes_4_io_out;
    io_output_left_left_left_right_left_right <= _pes_5_io_out;
    io_output_left_left_left_right_left <=
      io_output_left_left_left_right_left_left
      + io_output_left_left_left_right_left_right;
    io_output_left_left_left_right_right_left <= _pes_6_io_out;
    io_output_left_left_left_right_right_right <= _pes_7_io_out;
    io_output_left_left_left_right_right <=
      io_output_left_left_left_right_right_left
      + io_output_left_left_left_right_right_right;
    io_output_left_left_left_right <=
      io_output_left_left_left_right_left + io_output_left_left_left_right_right;
    io_output_left_left_left <=
      io_output_left_left_left_left + io_output_left_left_left_right;
    io_output_left_left_right_left_left_left <= _pes_8_io_out;
    io_output_left_left_right_left_left_right <= _pes_9_io_out;
    io_output_left_left_right_left_left <=
      io_output_left_left_right_left_left_left
      + io_output_left_left_right_left_left_right;
    io_output_left_left_right_left_right_left <= _pes_10_io_out;
    io_output_left_left_right_left_right_right <= _pes_11_io_out;
    io_output_left_left_right_left_right <=
      io_output_left_left_right_left_right_left
      + io_output_left_left_right_left_right_right;
    io_output_left_left_right_left <=
      io_output_left_left_right_left_left + io_output_left_left_right_left_right;
    io_output_left_left_right_right_left_left <= _pes_12_io_out;
    io_output_left_left_right_right_left_right <= _pes_13_io_out;
    io_output_left_left_right_right_left <=
      io_output_left_left_right_right_left_left
      + io_output_left_left_right_right_left_right;
    io_output_left_left_right_right_right_left <= _pes_14_io_out;
    io_output_left_left_right_right_right_right <= _pes_15_io_out;
    io_output_left_left_right_right_right <=
      io_output_left_left_right_right_right_left
      + io_output_left_left_right_right_right_right;
    io_output_left_left_right_right <=
      io_output_left_left_right_right_left + io_output_left_left_right_right_right;
    io_output_left_left_right <=
      io_output_left_left_right_left + io_output_left_left_right_right;
    io_output_left_left <= io_output_left_left_left + io_output_left_left_right;
    io_output_left_right_left_left_left_left <= _pes_16_io_out;
    io_output_left_right_left_left_left_right <= _pes_17_io_out;
    io_output_left_right_left_left_left <=
      io_output_left_right_left_left_left_left
      + io_output_left_right_left_left_left_right;
    io_output_left_right_left_left_right_left <= _pes_18_io_out;
    io_output_left_right_left_left_right_right <= _pes_19_io_out;
    io_output_left_right_left_left_right <=
      io_output_left_right_left_left_right_left
      + io_output_left_right_left_left_right_right;
    io_output_left_right_left_left <=
      io_output_left_right_left_left_left + io_output_left_right_left_left_right;
    io_output_left_right_left_right_left_left <= _pes_20_io_out;
    io_output_left_right_left_right_left_right <= _pes_21_io_out;
    io_output_left_right_left_right_left <=
      io_output_left_right_left_right_left_left
      + io_output_left_right_left_right_left_right;
    io_output_left_right_left_right_right_left <= _pes_22_io_out;
    io_output_left_right_left_right_right_right <= _pes_23_io_out;
    io_output_left_right_left_right_right <=
      io_output_left_right_left_right_right_left
      + io_output_left_right_left_right_right_right;
    io_output_left_right_left_right <=
      io_output_left_right_left_right_left + io_output_left_right_left_right_right;
    io_output_left_right_left <=
      io_output_left_right_left_left + io_output_left_right_left_right;
    io_output_left_right_right_left_left_left <= _pes_24_io_out;
    io_output_left_right_right_left_left_right <= _pes_25_io_out;
    io_output_left_right_right_left_left <=
      io_output_left_right_right_left_left_left
      + io_output_left_right_right_left_left_right;
    io_output_left_right_right_left_right_left <= _pes_26_io_out;
    io_output_left_right_right_left_right_right <= _pes_27_io_out;
    io_output_left_right_right_left_right <=
      io_output_left_right_right_left_right_left
      + io_output_left_right_right_left_right_right;
    io_output_left_right_right_left <=
      io_output_left_right_right_left_left + io_output_left_right_right_left_right;
    io_output_left_right_right_right_left_left <= _pes_28_io_out;
    io_output_left_right_right_right_left_right <= _pes_29_io_out;
    io_output_left_right_right_right_left <=
      io_output_left_right_right_right_left_left
      + io_output_left_right_right_right_left_right;
    io_output_left_right_right_right_right_left <= _pes_30_io_out;
    io_output_left_right_right_right_right_right <= _pes_31_io_out;
    io_output_left_right_right_right_right <=
      io_output_left_right_right_right_right_left
      + io_output_left_right_right_right_right_right;
    io_output_left_right_right_right <=
      io_output_left_right_right_right_left + io_output_left_right_right_right_right;
    io_output_left_right_right <=
      io_output_left_right_right_left + io_output_left_right_right_right;
    io_output_left_right <= io_output_left_right_left + io_output_left_right_right;
    io_output_left <= io_output_left_left + io_output_left_right;
    io_output_right_left_left_left_left_left <= _pes_32_io_out;
    io_output_right_left_left_left_left_right <= _pes_33_io_out;
    io_output_right_left_left_left_left <=
      io_output_right_left_left_left_left_left
      + io_output_right_left_left_left_left_right;
    io_output_right_left_left_left_right_left <= _pes_34_io_out;
    io_output_right_left_left_left_right_right <= _pes_35_io_out;
    io_output_right_left_left_left_right <=
      io_output_right_left_left_left_right_left
      + io_output_right_left_left_left_right_right;
    io_output_right_left_left_left <=
      io_output_right_left_left_left_left + io_output_right_left_left_left_right;
    io_output_right_left_left_right_left_left <= _pes_36_io_out;
    io_output_right_left_left_right_left_right <= _pes_37_io_out;
    io_output_right_left_left_right_left <=
      io_output_right_left_left_right_left_left
      + io_output_right_left_left_right_left_right;
    io_output_right_left_left_right_right_left <= _pes_38_io_out;
    io_output_right_left_left_right_right_right <= _pes_39_io_out;
    io_output_right_left_left_right_right <=
      io_output_right_left_left_right_right_left
      + io_output_right_left_left_right_right_right;
    io_output_right_left_left_right <=
      io_output_right_left_left_right_left + io_output_right_left_left_right_right;
    io_output_right_left_left <=
      io_output_right_left_left_left + io_output_right_left_left_right;
    io_output_right_left_right_left_left_left <= _pes_40_io_out;
    io_output_right_left_right_left_left_right <= _pes_41_io_out;
    io_output_right_left_right_left_left <=
      io_output_right_left_right_left_left_left
      + io_output_right_left_right_left_left_right;
    io_output_right_left_right_left_right_left <= _pes_42_io_out;
    io_output_right_left_right_left_right_right <= _pes_43_io_out;
    io_output_right_left_right_left_right <=
      io_output_right_left_right_left_right_left
      + io_output_right_left_right_left_right_right;
    io_output_right_left_right_left <=
      io_output_right_left_right_left_left + io_output_right_left_right_left_right;
    io_output_right_left_right_right_left_left <= _pes_44_io_out;
    io_output_right_left_right_right_left_right <= _pes_45_io_out;
    io_output_right_left_right_right_left <=
      io_output_right_left_right_right_left_left
      + io_output_right_left_right_right_left_right;
    io_output_right_left_right_right_right_left <= _pes_46_io_out;
    io_output_right_left_right_right_right_right <= _pes_47_io_out;
    io_output_right_left_right_right_right <=
      io_output_right_left_right_right_right_left
      + io_output_right_left_right_right_right_right;
    io_output_right_left_right_right <=
      io_output_right_left_right_right_left + io_output_right_left_right_right_right;
    io_output_right_left_right <=
      io_output_right_left_right_left + io_output_right_left_right_right;
    io_output_right_left <= io_output_right_left_left + io_output_right_left_right;
    io_output_right_right_left_left_left_left <= _pes_48_io_out;
    io_output_right_right_left_left_left_right <= _pes_49_io_out;
    io_output_right_right_left_left_left <=
      io_output_right_right_left_left_left_left
      + io_output_right_right_left_left_left_right;
    io_output_right_right_left_left_right_left <= _pes_50_io_out;
    io_output_right_right_left_left_right_right <= _pes_51_io_out;
    io_output_right_right_left_left_right <=
      io_output_right_right_left_left_right_left
      + io_output_right_right_left_left_right_right;
    io_output_right_right_left_left <=
      io_output_right_right_left_left_left + io_output_right_right_left_left_right;
    io_output_right_right_left_right_left_left <= _pes_52_io_out;
    io_output_right_right_left_right_left_right <= _pes_53_io_out;
    io_output_right_right_left_right_left <=
      io_output_right_right_left_right_left_left
      + io_output_right_right_left_right_left_right;
    io_output_right_right_left_right_right_left <= _pes_54_io_out;
    io_output_right_right_left_right_right_right <= _pes_55_io_out;
    io_output_right_right_left_right_right <=
      io_output_right_right_left_right_right_left
      + io_output_right_right_left_right_right_right;
    io_output_right_right_left_right <=
      io_output_right_right_left_right_left + io_output_right_right_left_right_right;
    io_output_right_right_left <=
      io_output_right_right_left_left + io_output_right_right_left_right;
    io_output_right_right_right_left_left_left <= _pes_56_io_out;
    io_output_right_right_right_left_left_right <= _pes_57_io_out;
    io_output_right_right_right_left_left <=
      io_output_right_right_right_left_left_left
      + io_output_right_right_right_left_left_right;
    io_output_right_right_right_left_right_left <= _pes_58_io_out;
    io_output_right_right_right_left_right_right <= _pes_59_io_out;
    io_output_right_right_right_left_right <=
      io_output_right_right_right_left_right_left
      + io_output_right_right_right_left_right_right;
    io_output_right_right_right_left <=
      io_output_right_right_right_left_left + io_output_right_right_right_left_right;
    io_output_right_right_right_right_left_left <= _pes_60_io_out;
    io_output_right_right_right_right_left_right <= _pes_61_io_out;
    io_output_right_right_right_right_left <=
      io_output_right_right_right_right_left_left
      + io_output_right_right_right_right_left_right;
    io_output_right_right_right_right_right_left <= _pes_62_io_out;
    io_output_right_right_right_right_right_right <= _pes_63_io_out;
    io_output_right_right_right_right_right <=
      io_output_right_right_right_right_right_left
      + io_output_right_right_right_right_right_right;
    io_output_right_right_right_right <=
      io_output_right_right_right_right_left + io_output_right_right_right_right_right;
    io_output_right_right_right <=
      io_output_right_right_right_left + io_output_right_right_right_right;
    io_output_right_right <= io_output_right_right_left + io_output_right_right_right;
    io_output_right <= io_output_right_left + io_output_right_right;
  end // always @(posedge)
  SinglePe pes_0 (
    .io_in_a (io_input_0_a),
    .io_in_b (io_input_0_b),
    .io_mode (io_mode),
    .io_out  (_pes_0_io_out)
  );
  SinglePe pes_1 (
    .io_in_a (io_input_1_a),
    .io_in_b (io_input_1_b),
    .io_mode (io_mode),
    .io_out  (_pes_1_io_out)
  );
  SinglePe pes_2 (
    .io_in_a (io_input_2_a),
    .io_in_b (io_input_2_b),
    .io_mode (io_mode),
    .io_out  (_pes_2_io_out)
  );
  SinglePe pes_3 (
    .io_in_a (io_input_3_a),
    .io_in_b (io_input_3_b),
    .io_mode (io_mode),
    .io_out  (_pes_3_io_out)
  );
  SinglePe pes_4 (
    .io_in_a (io_input_4_a),
    .io_in_b (io_input_4_b),
    .io_mode (io_mode),
    .io_out  (_pes_4_io_out)
  );
  SinglePe pes_5 (
    .io_in_a (io_input_5_a),
    .io_in_b (io_input_5_b),
    .io_mode (io_mode),
    .io_out  (_pes_5_io_out)
  );
  SinglePe pes_6 (
    .io_in_a (io_input_6_a),
    .io_in_b (io_input_6_b),
    .io_mode (io_mode),
    .io_out  (_pes_6_io_out)
  );
  SinglePe pes_7 (
    .io_in_a (io_input_7_a),
    .io_in_b (io_input_7_b),
    .io_mode (io_mode),
    .io_out  (_pes_7_io_out)
  );
  SinglePe pes_8 (
    .io_in_a (io_input_8_a),
    .io_in_b (io_input_8_b),
    .io_mode (io_mode),
    .io_out  (_pes_8_io_out)
  );
  SinglePe pes_9 (
    .io_in_a (io_input_9_a),
    .io_in_b (io_input_9_b),
    .io_mode (io_mode),
    .io_out  (_pes_9_io_out)
  );
  SinglePe pes_10 (
    .io_in_a (io_input_10_a),
    .io_in_b (io_input_10_b),
    .io_mode (io_mode),
    .io_out  (_pes_10_io_out)
  );
  SinglePe pes_11 (
    .io_in_a (io_input_11_a),
    .io_in_b (io_input_11_b),
    .io_mode (io_mode),
    .io_out  (_pes_11_io_out)
  );
  SinglePe pes_12 (
    .io_in_a (io_input_12_a),
    .io_in_b (io_input_12_b),
    .io_mode (io_mode),
    .io_out  (_pes_12_io_out)
  );
  SinglePe pes_13 (
    .io_in_a (io_input_13_a),
    .io_in_b (io_input_13_b),
    .io_mode (io_mode),
    .io_out  (_pes_13_io_out)
  );
  SinglePe pes_14 (
    .io_in_a (io_input_14_a),
    .io_in_b (io_input_14_b),
    .io_mode (io_mode),
    .io_out  (_pes_14_io_out)
  );
  SinglePe pes_15 (
    .io_in_a (io_input_15_a),
    .io_in_b (io_input_15_b),
    .io_mode (io_mode),
    .io_out  (_pes_15_io_out)
  );
  SinglePe pes_16 (
    .io_in_a (io_input_16_a),
    .io_in_b (io_input_16_b),
    .io_mode (io_mode),
    .io_out  (_pes_16_io_out)
  );
  SinglePe pes_17 (
    .io_in_a (io_input_17_a),
    .io_in_b (io_input_17_b),
    .io_mode (io_mode),
    .io_out  (_pes_17_io_out)
  );
  SinglePe pes_18 (
    .io_in_a (io_input_18_a),
    .io_in_b (io_input_18_b),
    .io_mode (io_mode),
    .io_out  (_pes_18_io_out)
  );
  SinglePe pes_19 (
    .io_in_a (io_input_19_a),
    .io_in_b (io_input_19_b),
    .io_mode (io_mode),
    .io_out  (_pes_19_io_out)
  );
  SinglePe pes_20 (
    .io_in_a (io_input_20_a),
    .io_in_b (io_input_20_b),
    .io_mode (io_mode),
    .io_out  (_pes_20_io_out)
  );
  SinglePe pes_21 (
    .io_in_a (io_input_21_a),
    .io_in_b (io_input_21_b),
    .io_mode (io_mode),
    .io_out  (_pes_21_io_out)
  );
  SinglePe pes_22 (
    .io_in_a (io_input_22_a),
    .io_in_b (io_input_22_b),
    .io_mode (io_mode),
    .io_out  (_pes_22_io_out)
  );
  SinglePe pes_23 (
    .io_in_a (io_input_23_a),
    .io_in_b (io_input_23_b),
    .io_mode (io_mode),
    .io_out  (_pes_23_io_out)
  );
  SinglePe pes_24 (
    .io_in_a (io_input_24_a),
    .io_in_b (io_input_24_b),
    .io_mode (io_mode),
    .io_out  (_pes_24_io_out)
  );
  SinglePe pes_25 (
    .io_in_a (io_input_25_a),
    .io_in_b (io_input_25_b),
    .io_mode (io_mode),
    .io_out  (_pes_25_io_out)
  );
  SinglePe pes_26 (
    .io_in_a (io_input_26_a),
    .io_in_b (io_input_26_b),
    .io_mode (io_mode),
    .io_out  (_pes_26_io_out)
  );
  SinglePe pes_27 (
    .io_in_a (io_input_27_a),
    .io_in_b (io_input_27_b),
    .io_mode (io_mode),
    .io_out  (_pes_27_io_out)
  );
  SinglePe pes_28 (
    .io_in_a (io_input_28_a),
    .io_in_b (io_input_28_b),
    .io_mode (io_mode),
    .io_out  (_pes_28_io_out)
  );
  SinglePe pes_29 (
    .io_in_a (io_input_29_a),
    .io_in_b (io_input_29_b),
    .io_mode (io_mode),
    .io_out  (_pes_29_io_out)
  );
  SinglePe pes_30 (
    .io_in_a (io_input_30_a),
    .io_in_b (io_input_30_b),
    .io_mode (io_mode),
    .io_out  (_pes_30_io_out)
  );
  SinglePe pes_31 (
    .io_in_a (io_input_31_a),
    .io_in_b (io_input_31_b),
    .io_mode (io_mode),
    .io_out  (_pes_31_io_out)
  );
  SinglePe pes_32 (
    .io_in_a (io_input_32_a),
    .io_in_b (io_input_32_b),
    .io_mode (io_mode),
    .io_out  (_pes_32_io_out)
  );
  SinglePe pes_33 (
    .io_in_a (io_input_33_a),
    .io_in_b (io_input_33_b),
    .io_mode (io_mode),
    .io_out  (_pes_33_io_out)
  );
  SinglePe pes_34 (
    .io_in_a (io_input_34_a),
    .io_in_b (io_input_34_b),
    .io_mode (io_mode),
    .io_out  (_pes_34_io_out)
  );
  SinglePe pes_35 (
    .io_in_a (io_input_35_a),
    .io_in_b (io_input_35_b),
    .io_mode (io_mode),
    .io_out  (_pes_35_io_out)
  );
  SinglePe pes_36 (
    .io_in_a (io_input_36_a),
    .io_in_b (io_input_36_b),
    .io_mode (io_mode),
    .io_out  (_pes_36_io_out)
  );
  SinglePe pes_37 (
    .io_in_a (io_input_37_a),
    .io_in_b (io_input_37_b),
    .io_mode (io_mode),
    .io_out  (_pes_37_io_out)
  );
  SinglePe pes_38 (
    .io_in_a (io_input_38_a),
    .io_in_b (io_input_38_b),
    .io_mode (io_mode),
    .io_out  (_pes_38_io_out)
  );
  SinglePe pes_39 (
    .io_in_a (io_input_39_a),
    .io_in_b (io_input_39_b),
    .io_mode (io_mode),
    .io_out  (_pes_39_io_out)
  );
  SinglePe pes_40 (
    .io_in_a (io_input_40_a),
    .io_in_b (io_input_40_b),
    .io_mode (io_mode),
    .io_out  (_pes_40_io_out)
  );
  SinglePe pes_41 (
    .io_in_a (io_input_41_a),
    .io_in_b (io_input_41_b),
    .io_mode (io_mode),
    .io_out  (_pes_41_io_out)
  );
  SinglePe pes_42 (
    .io_in_a (io_input_42_a),
    .io_in_b (io_input_42_b),
    .io_mode (io_mode),
    .io_out  (_pes_42_io_out)
  );
  SinglePe pes_43 (
    .io_in_a (io_input_43_a),
    .io_in_b (io_input_43_b),
    .io_mode (io_mode),
    .io_out  (_pes_43_io_out)
  );
  SinglePe pes_44 (
    .io_in_a (io_input_44_a),
    .io_in_b (io_input_44_b),
    .io_mode (io_mode),
    .io_out  (_pes_44_io_out)
  );
  SinglePe pes_45 (
    .io_in_a (io_input_45_a),
    .io_in_b (io_input_45_b),
    .io_mode (io_mode),
    .io_out  (_pes_45_io_out)
  );
  SinglePe pes_46 (
    .io_in_a (io_input_46_a),
    .io_in_b (io_input_46_b),
    .io_mode (io_mode),
    .io_out  (_pes_46_io_out)
  );
  SinglePe pes_47 (
    .io_in_a (io_input_47_a),
    .io_in_b (io_input_47_b),
    .io_mode (io_mode),
    .io_out  (_pes_47_io_out)
  );
  SinglePe pes_48 (
    .io_in_a (io_input_48_a),
    .io_in_b (io_input_48_b),
    .io_mode (io_mode),
    .io_out  (_pes_48_io_out)
  );
  SinglePe pes_49 (
    .io_in_a (io_input_49_a),
    .io_in_b (io_input_49_b),
    .io_mode (io_mode),
    .io_out  (_pes_49_io_out)
  );
  SinglePe pes_50 (
    .io_in_a (io_input_50_a),
    .io_in_b (io_input_50_b),
    .io_mode (io_mode),
    .io_out  (_pes_50_io_out)
  );
  SinglePe pes_51 (
    .io_in_a (io_input_51_a),
    .io_in_b (io_input_51_b),
    .io_mode (io_mode),
    .io_out  (_pes_51_io_out)
  );
  SinglePe pes_52 (
    .io_in_a (io_input_52_a),
    .io_in_b (io_input_52_b),
    .io_mode (io_mode),
    .io_out  (_pes_52_io_out)
  );
  SinglePe pes_53 (
    .io_in_a (io_input_53_a),
    .io_in_b (io_input_53_b),
    .io_mode (io_mode),
    .io_out  (_pes_53_io_out)
  );
  SinglePe pes_54 (
    .io_in_a (io_input_54_a),
    .io_in_b (io_input_54_b),
    .io_mode (io_mode),
    .io_out  (_pes_54_io_out)
  );
  SinglePe pes_55 (
    .io_in_a (io_input_55_a),
    .io_in_b (io_input_55_b),
    .io_mode (io_mode),
    .io_out  (_pes_55_io_out)
  );
  SinglePe pes_56 (
    .io_in_a (io_input_56_a),
    .io_in_b (io_input_56_b),
    .io_mode (io_mode),
    .io_out  (_pes_56_io_out)
  );
  SinglePe pes_57 (
    .io_in_a (io_input_57_a),
    .io_in_b (io_input_57_b),
    .io_mode (io_mode),
    .io_out  (_pes_57_io_out)
  );
  SinglePe pes_58 (
    .io_in_a (io_input_58_a),
    .io_in_b (io_input_58_b),
    .io_mode (io_mode),
    .io_out  (_pes_58_io_out)
  );
  SinglePe pes_59 (
    .io_in_a (io_input_59_a),
    .io_in_b (io_input_59_b),
    .io_mode (io_mode),
    .io_out  (_pes_59_io_out)
  );
  SinglePe pes_60 (
    .io_in_a (io_input_60_a),
    .io_in_b (io_input_60_b),
    .io_mode (io_mode),
    .io_out  (_pes_60_io_out)
  );
  SinglePe pes_61 (
    .io_in_a (io_input_61_a),
    .io_in_b (io_input_61_b),
    .io_mode (io_mode),
    .io_out  (_pes_61_io_out)
  );
  SinglePe pes_62 (
    .io_in_a (io_input_62_a),
    .io_in_b (io_input_62_b),
    .io_mode (io_mode),
    .io_out  (_pes_62_io_out)
  );
  SinglePe pes_63 (
    .io_in_a (io_input_63_a),
    .io_in_b (io_input_63_b),
    .io_mode (io_mode),
    .io_out  (_pes_63_io_out)
  );
  assign io_output = io_output_left + io_output_right;
endmodule

